version: "3"
services:
  exam-app:
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules  # ← CRÍTICO: evita sobreescribir node_modules
    container_name: exam-app
